### ISSUE TITLE
lon/lat order for reverse

### ISSUE THREAD

**Issue by missinglink** [pelias/compare#20]
Heya,

I recently tried to copy the coordinates from an Australian addresses from the geojson body and paste it into the 'Point' field for the 'Reverse Geocode' API and found that it ended up in the North Pacific Ocean 😱 

I think the cause of this is that the input box accepts `lat/lon` when the geojson spec specifies `lon/lat`.

This is obviously the most contentious topic in geo! 😆 😢 
... but I think for the sake of clarity we should adhere to the [geojson spec](https://tools.ietf.org/html/rfc7946#appendix-A.1) and the [Pelias documentation](https://github.com/pelias/documentation/blob/master/response.md#coordinates) where possible?

<img width="480" alt="Screenshot 2020-05-09 at 12 06 02" src="https://user-images.githubusercontent.com/738069/81471067-d16c4880-91ee-11ea-9109-104bdf779d68.png">
<img width="226" alt="Screenshot 2020-05-09 at 12 06 09" src="https://user-images.githubusercontent.com/738069/81471068-d29d7580-91ee-11ea-8b50-a9e57f90f0d9.png">

**Comment by blackmad** [comment]
d'oh. Agreed it should be lon/lat since that's what pelias uses everywhere. Flipping/fixing now.

**Comment by blackmad** [comment]
PR in https://github.com/pelias/compare/compare/fix-latlng-order-and-input?expand=1

**Comment by Joxit** [comment]
Done with #22
