### ISSUE TITLE
Limit precision of lat/lon coordinates choosen by map

### ISSUE THREAD

**Issue by orangejulius** [pelias/compare#26]
A great follow up addition to #24 would be to limit the precision of lat/lons when choosing via the map or via "locate me"

Current behavior generates coordinates like `40.67483815011894,-73.965594234261`, which XKCD [covered](https://xkcd.com/2170/) specifically:
![Screenshot_2020-05-28_11-28-09](https://user-images.githubusercontent.com/111716/83179080-548a0b80-a0d6-11ea-893f-022c1c01818c.png)

It would be awesome for usability if these were shorter :)

**Comment by blackmad** [comment]
pulled this down to 6 decimal places, lmk if you want to go to FIVE or even FOUR

**Comment by blackmad** [comment]
https://github.com/pelias/compare/commit/b16b382c0c839a3ef8c0269ea4f972fd198a161a

**Comment by orangejulius** [comment]
6 is perfect
