### ISSUE TITLE
Layout adjustments for better screenshots

### ISSUE THREAD

**Issue by orangejulius** [pelias/compare#29]
I (and probably others) often generate screenshots of the output from the compare app to paste into GitHub issues. It's useful to have a screenshot, since the results of a given link can change over time.

The old compare app let us generate screenshots with _just_ the query text and the results, which were very concise. There wasn't much space between the two elements we care about.
![Screenshot_2020-03-04_13-33-33](https://user-images.githubusercontent.com/111716/84816114-dc25b480-afc8-11ea-8a04-d9518504bc13.png)

The new compare app has the submit button which adds a bunch of empty space between the two elements relevant for screenshots.

![Screenshot_2020-06-16_11-55-47](https://user-images.githubusercontent.com/111716/84816193-f8295600-afc8-11ea-8993-61685a1e82eb.png)

While it's not an enormous deal at all, it would be really nice to find an adjustment to the layout that makes these screenshots better.

Maybe we can move the submit button to the same line as the query, all the way on the right? I can see how that might be worse from a usability perspective, so I'm open to other ideas as well.

**Comment by blackmad** [comment]
moving the submit button up is fine.

Is it important that "performance optimization: excluding 'address' layer" gets shown so often? maybe we should consider making that less verbose at the api level?
