### ISSUE TITLE
JSON view

### ISSUE THREAD

**Issue by missinglink** [pelias/compare#4]
Heya,

I'm seeing some alarming red circles and also some "0" entries where it should be a string?

![Screenshot_20200306-230439](https://user-images.githubusercontent.com/738069/76126276-f7167f00-5ffe-11ea-926a-38f868482aed.jpg)

Android, chrome beta

**Comment by missinglink** [comment]
Seems I'm not the only one seeing this, https://github.com/pelias/polylines/issues/244

@blackmad is there some way we can at least get rid of those 0's which make it look like some properties are arrays when they aren't?

**Comment by blackmad** [comment]
super sorry, don't know why I just saw the notification for this.

yes will look into this asap.

**Comment by blackmad** [comment]
this is two little issues

1) was rendering linkifed GIDs as lists. FIXED
2) those little red circles are supposed to be so you can expand/collapse parts of the JSON if you are hunting around. Since they're confusing folks and I don't know that they'll be used often, I just got rid of them for now.

**Comment by blackmad** [comment]
also added a copy json button to make it even easier https://github.com/pelias/compare/pull/11
