### ISSUE TITLE
auto generate docker images

### ISSUE THREAD

**Issue by missinglink** [pelias/compare#6]
we should set this repo up to auto generate docker images the same way we do for the other repos.

https://hub.docker.com/r/pelias/compare

**Comment by orangejulius** [comment]
We don't generate any Docker images for the compare app, since it's hosted on GitHub pages, and there's currently not even a `Dockerfile`.

I'm closing this assuming that we don't need to do anything, but if there's a clever use for a Docker image we could certainly add one.
