### ISSUE TITLE
URL encoding of extra params

### ISSUE THREAD

**Issue by missinglink** [pelias/compare#7]
![Screenshot_20200309-193904__01](https://user-images.githubusercontent.com/738069/76246344-d0925700-623d-11ea-968e-56ed3f722e9d.jpg)

If possible, the 'extra params' section should be url decoded for display (eg. the commas in the image above)

**Comment by orangejulius** [comment]
:+1: I was just going to open an issue for this as well.

The use case is that we often copy just the parameters (or, more commonly, just the `path` part of a URL to Pelias) for sharing around, putting in GitHub issues.

In those cases, the human friendlyness of decoded URLs or paths is preferable.
