### ISSUE TITLE
Allow pasting full query into the "search path" field

### ISSUE THREAD

**Issue by orangejulius** [pelias/compare#8]
A common workflow when debugging is to paste a full Pelias query into the compare app.

We've specifically designed our [acceptance testing library](https://github.com/pelias/fuzzy-tester) to emit these query paths (see https://github.com/pelias/fuzzy-tester/pull/171).

Right now, when navigating to the compare app and pasting a full query, the app generates an error saying the text field must be filled:
![Screenshot_2020-03-10_14-36-21](https://user-images.githubusercontent.com/111716/76361726-d4c18180-62dc-11ea-81a2-2da9c5830e9f.png)

**Comment by orangejulius** [comment]
Ah, turns out it was a little hard to capture a screenshot of this, as the error goes away as soon as focus is lost. Let me know if the behavior I'm describing isn't clear.

**Comment by missinglink** [comment]
I've also noticed times when the `?text=` text is visible in another input box but when I hit search I need to add it to the top input to continue.
